# -*- coding: utf-8 -*-
"""Spotify EDA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19T9gfyFUC5S_vBlUMrIaLXCepCrt-rWJ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/EDA/Spotify EDA/Spotify_Youtube.csv')

df.head()

df1 = df.copy()

#Dropping unwanted columns
unwanted_cols = ['Unnamed: 0','Url_spotify','Uri','Url_youtube']

df.drop(columns=unwanted_cols,inplace=True)

df.shape

df.isnull().sum().sort_values(ascending=False)

df.dropna(inplace=True)

df.isnull().sum()

df.dtypes

df.nunique()

df.shape

"""EDA"""

view = df.groupby('Artist')['Views'].agg('sum').reset_index().sort_values('Views',ascending=False).head(10)
view

view.set_index('Artist',inplace=True)
view.plot(kind='bar',color='g')
plt.xlabel('Artist')
plt.ylabel('Views')
plt.title("Top 10 Artists in the World According to Views")
plt.xticks(rotation=70)
plt.show()

view_2 = df.groupby('Album')['Likes'].agg('sum').reset_index().sort_values('Likes',ascending=False).head(10)
view_2

sns.barplot(data=view_2,x="Likes",y="Album")
plt.title("Top 10 Albums According to Likes")
plt.show()

view_3 = df.groupby('Artist')['Likes'].agg('sum').reset_index().sort_values('Likes',ascending=False).head(10)

view_3

sns.barplot(data=view_3,x="Likes",y="Artist")
plt.title("Top 10 Artists According to Likes")
plt.show()

#Most COmmented Artist on Youtube
ax = df.groupby('Artist')['Comments'].sum().reset_index().sort_values('Comments',ascending=False).head(10)
ax

sns.barplot(data=ax,x="Comments",y="Artist")
plt.title("Top 10 Most Commented Artists")
plt.show()

tc = df.groupby('Track').agg({'Likes':'sum','Views':'sum','Comments':'sum'}).reset_index().sort_values('Views',ascending=False).head(10)
tc

plt.barh(tc['Track'],tc['Views'],color='g')
plt.title("Top 10 most Viewed Tracks")
plt.show()

tc = df.groupby('Track').agg({'Likes':'sum','Views':'sum','Comments':'sum'}).reset_index().sort_values('Comments',ascending=False).head(10)

plt.barh(tc['Track'],tc['Comments'],color='g')
plt.title("Top 10 most Commented Tracks on Youtube")
plt.show()

tc = df.groupby('Track').agg({'Likes':'sum','Views':'sum','Comments':'sum'}).reset_index().sort_values('Likes',ascending=False).head(10)

plt.barh(tc['Track'],tc['Likes'],color='g')
plt.title("Top 10 most Liked Tracks on Youtube")
plt.show()

df.corr()

heat_map = df.corr()
plt.figure(figsize=(10,10))

sns.heatmap(heat_map,annot=True,fmt='.1f',linecolor='black',linewidth=0.6)
plt.axis('tight')
plt.show()



